// NOTIFICATION
export const NOTIFICATIONS_GET = "NOTIFICATIONS_GET";
export const NOTIFICATIONS_PUSH = "NOTIFICATIONS_PUSH";
export const NOTIFICATIONS_REMOVE = "NOTIFICATIONS_REMOVE";
export const NOTIFICATIONS_CLEAN = "NOTIFICATIONS_CLEAN";
